spring:
  application:
    name: uaa
  config:
    import: optional:configserver:http://localhost:8088/
  data:
    mongodb:
      authentication-database: admin
      database: uaa
      host: localhost
      port: 27017
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8083
mongock:
  migration-scan-package: com.noob.uaa.dbmigration