spring:
  application:
    name: post
  config:
    import: optional:configserver:http://localhost:8088/
  data:
    mongodb:
      authentication-database: admin
      database: post
      host: localhost
      port: 27017
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
server:
  port: 8082

application:
  config:
    uaa-url: http://localhost:8083/api/uaa