spring:
  application:
    name: gateway
  main:
    allow-bean-definition-overriding: true
  config:
    import: optional:configserver:http://localhost:8088/
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: post
          uri: http://localhost:8082
          predicates:
            - Path=/api/post/**
        - id: uaa
          uri: http://localhost:8083
          predicates:
            - Path=/api/uaa/**

    data:
      mongodb:
        database: uaa
        host: localhost
        port: 27017
        authentication-database: admin
eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

server:
  port: 8080

application:
  jwtCookieName: noob
  jwtSecret: faiuhfauhfvjijpaffaJhyuhd13ygffaDOcmMCSnoobD9UF9A8F98AYFE76uiyiuIUaY80jffTkddacvbugugfauyfb87681823jbjBYXYTFAu1982kjc
  jwtExpirationsMs: 86400000

