eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: post
  data:
    mongodb:
      authentication-database: admin
      database: post
      host: localhost
      port: 27017
server:
  port: 8082